name: Auto Sync and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'adumannn'
          git config --global user.email 'abdurahmanuly.shymkent@gmail.com'
          git commit -m "Update site files" || echo "No changes to commit"
          git push origin main
          
      - name: Deploy to Vercel
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run: |
          curl -X POST $VERCEL_DEPLOY_HOOK 